config_name: withattention

# path related
data_path: /home/seito/hdd/dsets/coco
caption_file_path: annotations/captions_train2017.txt
log_dir: ../log
result_dir: ../out

max_epoch: 30
num_worker: 4

min_freq: 5
max_len: 30
batch_size: 64
lr: 0.0001
beta1: 0.9
beta2: 0.999
# cnn architecture, choose from 
# 'resnet[18|34|50|101|152]', 'resnext50_32x4d', 'resnext101_32x8d', 'wide_resnet[50|101]_2'
cnn_arch: resnet101
attention: True

spatial_size: 7
emb_dim: 300
memory_dim: 512
dropout_p: 0
ss_prob: 0
